
CREATE DATABASE refaccionaria;
USE refaccionaria;

CREATE TABLE producto(
    id INT AUTO_INCREMENT PRIMARY KEY,
    producto VARCHAR(50)
);

CREATE TABLE vendidos(
    id_vendidos INT AUTO_INCREMENT PRIMARY KEY,
    producto VARCHAR(30),
    descripcion VARCHAR(30),
    cantidad INT,
    precio INT
);

CREATE TABLE nota(
    id_nota INT AUTO_INCREMENT PRIMARY KEY,
    fecha VARCHAR(10),
    hora VARCHAR(10),
    total INT
);


INSERT INTO `producto`( `producto`) VALUES ("ACCESORIO");
INSERT INTO `producto`( `producto`) VALUES ("ACEITE");
INSERT INTO `producto`( `producto`) VALUES ("ACEITE CUBETA");
INSERT INTO `producto`( `producto`) VALUES ("ACIDO");
INSERT INTO `producto`( `producto`) VALUES ("ADAPTADOR");
INSERT INTO `producto`( `producto`) VALUES ("ADITIVO");
INSERT INTO `producto`( `producto`) VALUES ("AFLOJATODO");
INSERT INTO `producto`( `producto`) VALUES ("AGUA BATERIA");
INSERT INTO `producto`( `producto`) VALUES ("AHORCADOR");
INSERT INTO `producto`( `producto`) VALUES ("AJUSTADOR");
INSERT INTO `producto`( `producto`) VALUES ("ALTERNADOR");
INSERT INTO `producto`( `producto`) VALUES ("AMORTIGUADOR");
INSERT INTO `producto`( `producto`) VALUES ("AMORTIGUADOR DELANTERO");
INSERT INTO `producto`( `producto`) VALUES ("AMORTIGUADOR TRASERO");
INSERT INTO `producto`( `producto`) VALUES ("ANCLA");
INSERT INTO `producto`( `producto`) VALUES ("ANILLO");
INSERT INTO `producto`( `producto`) VALUES ("ANTENA");
INSERT INTO `producto`( `producto`) VALUES ("ANTICONGELANTE");
INSERT INTO `producto`( `producto`) VALUES ("ARBOL");
INSERT INTO `producto`( `producto`) VALUES ("ARILLO");
INSERT INTO `producto`( `producto`) VALUES ("ARNES");
INSERT INTO `producto`( `producto`) VALUES ("AROMA");
INSERT INTO `producto`( `producto`) VALUES ("ASPA");
INSERT INTO `producto`( `producto`) VALUES ("AUMENTO");
INSERT INTO `producto`( `producto`) VALUES ("AUTOMATICO");
INSERT INTO `producto`( `producto`) VALUES ("AVANCE");
INSERT INTO `producto`( `producto`) VALUES ("BALANCIN");
INSERT INTO `producto`( `producto`) VALUES ("BALATA");
INSERT INTO `producto`( `producto`) VALUES ("BALERO");
INSERT INTO `producto`( `producto`) VALUES ("BANDA");
INSERT INTO `producto`( `producto`) VALUES ("BARRA");
INSERT INTO `producto`( `producto`) VALUES ("BARRA");
INSERT INTO `producto`( `producto`) VALUES ("BASE");
INSERT INTO `producto`( `producto`) VALUES ("BATERIA");
INSERT INTO `producto`( `producto`) VALUES ("BAYONETA");
INSERT INTO `producto`( `producto`) VALUES ("BENDIX");
INSERT INTO `producto`( `producto`) VALUES ("BOMBA DE FRENOS");
INSERT INTO `producto`( `producto`) VALUES ("BICEL");
INSERT INTO `producto`( `producto`) VALUES ("BICERA");
INSERT INTO `producto`( `producto`) VALUES ("BIELETA");
INSERT INTO `producto`( `producto`) VALUES ("BIRLO");
INSERT INTO `producto`( `producto`) VALUES ("BOBINA");
INSERT INTO `producto`( `producto`) VALUES ("BOCA");
INSERT INTO `producto`( `producto`) VALUES ("BOCINA");
INSERT INTO `producto`( `producto`) VALUES ("BOMBA");
INSERT INTO `producto`( `producto`) VALUES ("BOSTER");
INSERT INTO `producto`( `producto`) VALUES ("BOTON");
INSERT INTO `producto`( `producto`) VALUES ("BRACK");
INSERT INTO `producto`( `producto`) VALUES ("BRAZO");
INSERT INTO `producto`( `producto`) VALUES ("BRIDA");
INSERT INTO `producto`( `producto`) VALUES ("BRINCADOR");
INSERT INTO `producto`( `producto`) VALUES ("BISAGRA");
INSERT INTO `producto`( `producto`) VALUES ("BROCE");
INSERT INTO `producto`( `producto`) VALUES ("BUJE");
INSERT INTO `producto`( `producto`) VALUES ("BUJIA");
INSERT INTO `producto`( `producto`) VALUES ("BULBO");
INSERT INTO `producto`( `producto`) VALUES ("BUZO");
INSERT INTO `producto`( `producto`) VALUES ("CABEZA");
INSERT INTO `producto`( `producto`) VALUES ("CABLE");
INSERT INTO `producto`( `producto`) VALUES ("CACAHUATE");
INSERT INTO `producto`( `producto`) VALUES ("CAJA");
INSERT INTO `producto`( `producto`) VALUES ("CALAVERA");
INSERT INTO `producto`( `producto`) VALUES ("CALIPER");
INSERT INTO `producto`( `producto`) VALUES ("CAMPANA");
INSERT INTO `producto`( `producto`) VALUES ("CAMPOS");
INSERT INTO `producto`( `producto`) VALUES ("CANDADO DE TRANSMISION");
INSERT INTO `producto`( `producto`) VALUES ("CANDELERO");
INSERT INTO `producto`( `producto`) VALUES ("CANTONERA");
INSERT INTO `producto`( `producto`) VALUES ("CARBON");
INSERT INTO `producto`( `producto`) VALUES ("CARBUCLIN");
INSERT INTO `producto`( `producto`) VALUES ("CARBURADOR");
INSERT INTO `producto`( `producto`) VALUES ("CARCAZA");
INSERT INTO `producto`( `producto`) VALUES ("CARRETILLA");
INSERT INTO `producto`( `producto`) VALUES ("CARRITO DE CAJA");
INSERT INTO `producto`( `producto`) VALUES ("CARTER");
INSERT INTO `producto`( `producto`) VALUES ("CASCO");
INSERT INTO `producto`( `producto`) VALUES ("CEBOLLA");
INSERT INTO `producto`( `producto`) VALUES ("CENICERO");
INSERT INTO `producto`( `producto`) VALUES ("CERA");
INSERT INTO `producto`( `producto`) VALUES ("SEGURO CLUTCH");
INSERT INTO `producto`( `producto`) VALUES ("CHAPA");
INSERT INTO `producto`( `producto`) VALUES ("CHAVETA");
INSERT INTO `producto`( `producto`) VALUES ("CHICOTE");
INSERT INTO `producto`( `producto`) VALUES ("CHISGUETERO");
INSERT INTO `producto`( `producto`) VALUES ("CHUPON");
INSERT INTO `producto`( `producto`) VALUES ("CIGUEÑAL");
INSERT INTO `producto`( `producto`) VALUES ("CILINDRO");
INSERT INTO `producto`( `producto`) VALUES ("CINCHO");
INSERT INTO `producto`( `producto`) VALUES ("CINTA");
INSERT INTO `producto`( `producto`) VALUES ("CLUTCH");
INSERT INTO `producto`( `producto`) VALUES ("CODERA");
INSERT INTO `producto`( `producto`) VALUES ("CODO");
INSERT INTO `producto`( `producto`) VALUES ("COFRE");
INSERT INTO `producto`( `producto`) VALUES ("COLADERA");
INSERT INTO `producto`( `producto`) VALUES ("COLLARIN");
INSERT INTO `producto`( `producto`) VALUES ("CONCHA");
INSERT INTO `producto`( `producto`) VALUES ("CONDENSADOR");
INSERT INTO `producto`( `producto`) VALUES ("CONJUNTO");
INSERT INTO `producto`( `producto`) VALUES ("COPLE");
INSERT INTO `producto`( `producto`) VALUES ("CREMALLERA");
INSERT INTO `producto`( `producto`) VALUES ("CRUCETA");
INSERT INTO `producto`( `producto`) VALUES ("CUARTO");
INSERT INTO `producto`( `producto`) VALUES ("CUBIERTA");
INSERT INTO `producto`( `producto`) VALUES ("CUBREPOLVO");
INSERT INTO `producto`( `producto`) VALUES ("CUÑA");
INSERT INTO `producto`( `producto`) VALUES ("DEFENSA");
INSERT INTO `producto`( `producto`) VALUES ("DEPOSITO");
INSERT INTO `producto`( `producto`) VALUES ("DESLIZADOR");
INSERT INTO `producto`( `producto`) VALUES ("DIAFRAGMA");
INSERT INTO `producto`( `producto`) VALUES ("LUBER DIESEL 50 19LT");
INSERT INTO `producto`( `producto`) VALUES ("DIFERENCIA");
INSERT INTO `producto`( `producto`) VALUES ("DISCO");
INSERT INTO `producto`( `producto`) VALUES ("DISTRIBUIDOR");
INSERT INTO `producto`( `producto`) VALUES ("DONA");
INSERT INTO `producto`( `producto`) VALUES ("CINTURON");
INSERT INTO `producto`( `producto`) VALUES ("EJE");
INSERT INTO `producto`( `producto`) VALUES ("ELEVADOR");
INSERT INTO `producto`( `producto`) VALUES ("EMBLEMA");
INSERT INTO `producto`( `producto`) VALUES ("EMBUDO");
INSERT INTO `producto`( `producto`) VALUES ("ENCENDEDOR");
INSERT INTO `producto`( `producto`) VALUES ("ENGRANE");
INSERT INTO `producto`( `producto`) VALUES ("ESCAPE COMBI");
INSERT INTO `producto`( `producto`) VALUES ("ESCOBILLA");
INSERT INTO `producto`( `producto`) VALUES ("ESFERA");
INSERT INTO `producto`( `producto`) VALUES ("ESMERIL");
INSERT INTO `producto`( `producto`) VALUES ("ESPEJO DERECHO");
INSERT INTO `producto`( `producto`) VALUES ("ESPEJO IZQUIERDO");
INSERT INTO `producto`( `producto`) VALUES ("ESPIGA");
INSERT INTO `producto`( `producto`) VALUES ("ESPREA");
INSERT INTO `producto`( `producto`) VALUES ("ESTABILIZADOR");
INSERT INTO `producto`( `producto`) VALUES ("ESTERILLA");
INSERT INTO `producto`( `producto`) VALUES ("ESTRIBO");
INSERT INTO `producto`( `producto`) VALUES ("FACIA");
INSERT INTO `producto`( `producto`) VALUES ("FANCLUTCH");
INSERT INTO `producto`( `producto`) VALUES ("FARO");
INSERT INTO `producto`( `producto`) VALUES ("FILTRO");
INSERT INTO `producto`( `producto`) VALUES ("FILTRO ACEITE");
INSERT INTO `producto`( `producto`) VALUES ("FILTRO AIRE");
INSERT INTO `producto`( `producto`) VALUES ("FILTRO GAS");
INSERT INTO `producto`( `producto`) VALUES ("FILTRO DE PROMOCION");
INSERT INTO `producto`( `producto`) VALUES ("FLECHA");
INSERT INTO `producto`( `producto`) VALUES ("FLOTADOR");
INSERT INTO `producto`( `producto`) VALUES ("FOCO");
INSERT INTO `producto`( `producto`) VALUES ("FUNDA");
INSERT INTO `producto`( `producto`) VALUES ("FUSIBLE");
INSERT INTO `producto`( `producto`) VALUES ("GALLITO");
INSERT INTO `producto`( `producto`) VALUES ("GATO");
INSERT INTO `producto`( `producto`) VALUES ("GENERADOR");
INSERT INTO `producto`( `producto`) VALUES ("GOMA");
INSERT INTO `producto`( `producto`) VALUES ("GRAPA");
INSERT INTO `producto`( `producto`) VALUES ("GRASA");
INSERT INTO `producto`( `producto`) VALUES ("GUANTERA");
INSERT INTO `producto`( `producto`) VALUES ("GUIA");
INSERT INTO `producto`( `producto`) VALUES ("HERRAMIENTA");
INSERT INTO `producto`( `producto`) VALUES ("HOMOCINETICA");
INSERT INTO `producto`( `producto`) VALUES ("HORQUILLA");
INSERT INTO `producto`( `producto`) VALUES ("HUESO");
INSERT INTO `producto`( `producto`) VALUES ("HULE");
INSERT INTO `producto`( `producto`) VALUES ("IMPORTE");
INSERT INTO `producto`( `producto`) VALUES ("INYECTOR");
INSERT INTO `producto`( `producto`) VALUES ("BALATA TRAS");
INSERT INTO `producto`( `producto`) VALUES ("JUNTA");
INSERT INTO `producto`( `producto`) VALUES ("KIT");
INSERT INTO `producto`( `producto`) VALUES ("KIT BALERO");
INSERT INTO `producto`( `producto`) VALUES ("KIT DE REFACCIONES");
INSERT INTO `producto`( `producto`) VALUES ("LAINA");
INSERT INTO `producto`( `producto`) VALUES ("LAPIZ");
INSERT INTO `producto`( `producto`) VALUES ("LIGA");
INSERT INTO `producto`( `producto`) VALUES ("LIMPIADOR");
INSERT INTO `producto`( `producto`) VALUES ("LIQUIDO");
INSERT INTO `producto`( `producto`) VALUES ("LLAVE");
INSERT INTO `producto`( `producto`) VALUES ("LODERA");
INSERT INTO `producto`( `producto`) VALUES ("MACHETA");
INSERT INTO `producto`( `producto`) VALUES ("MANGO");
INSERT INTO `producto`( `producto`) VALUES ("MANGUERA");
INSERT INTO `producto`( `producto`) VALUES ("MANIJA");
INSERT INTO `producto`( `producto`) VALUES ("MANOPLA");
INSERT INTO `producto`( `producto`) VALUES ("MARCHA");
INSERT INTO `producto`( `producto`) VALUES ("MARCO");
INSERT INTO `producto`( `producto`) VALUES ("MARIPOSA DE CHICOTE");
INSERT INTO `producto`( `producto`) VALUES ("MAZA");
INSERT INTO `producto`( `producto`) VALUES ("MECANISMO");
INSERT INTO `producto`( `producto`) VALUES ("METAL");
INSERT INTO `producto`( `producto`) VALUES ("MICA");
INSERT INTO `producto`( `producto`) VALUES ("MODULO");
INSERT INTO `producto`( `producto`) VALUES ("MOLDURA");
INSERT INTO `producto`( `producto`) VALUES ("MOTOR");
INSERT INTO `producto`( `producto`) VALUES ("MUELA");
INSERT INTO `producto`( `producto`) VALUES ("NAVAJA");
INSERT INTO `producto`( `producto`) VALUES ("ESCOBILLA SD 1.5");
INSERT INTO `producto`( `producto`) VALUES ("NUDO");
INSERT INTO `producto`( `producto`) VALUES ("OPRESOR");
INSERT INTO `producto`( `producto`) VALUES ("PALANCA");
INSERT INTO `producto`( `producto`) VALUES ("PAPEL");
INSERT INTO `producto`( `producto`) VALUES ("PARASOL");
INSERT INTO `producto`( `producto`) VALUES ("PARRILLA");
INSERT INTO `producto`( `producto`) VALUES ("PATILLA");
INSERT INTO `producto`( `producto`) VALUES ("PEDAL");
INSERT INTO `producto`( `producto`) VALUES ("PEGAMENTO");
INSERT INTO `producto`( `producto`) VALUES ("PERILLA");
INSERT INTO `producto`( `producto`) VALUES ("PERNO");
INSERT INTO `producto`( `producto`) VALUES ("PIPA");
INSERT INTO `producto`( `producto`) VALUES ("PISO");
INSERT INTO `producto`( `producto`) VALUES ("PISTON");
INSERT INTO `producto`( `producto`) VALUES ("PLACA");
INSERT INTO `producto`( `producto`) VALUES ("PLAFON");
INSERT INTO `producto`( `producto`) VALUES ("PLASTIACERO");
INSERT INTO `producto`( `producto`) VALUES ("PLATILLO");
INSERT INTO `producto`( `producto`) VALUES ("PLATINO");
INSERT INTO `producto`( `producto`) VALUES ("PLUMA");
INSERT INTO `producto`( `producto`) VALUES ("POLEA");
INSERT INTO `producto`( `producto`) VALUES ("PORTA CARBON");
INSERT INTO `producto`( `producto`) VALUES ("PORTA COLLARIN");
INSERT INTO `producto`( `producto`) VALUES ("PORTA FUSIBLE");
INSERT INTO `producto`( `producto`) VALUES ("PORTA PLACA");
INSERT INTO `producto`( `producto`) VALUES ("PORTA PLATINO");
INSERT INTO `producto`( `producto`) VALUES ("PORTA RETEN");
INSERT INTO `producto`( `producto`) VALUES ("PURGADOR");
INSERT INTO `producto`( `producto`) VALUES ("QUAKER");
INSERT INTO `producto`( `producto`) VALUES ("QUIMICO");
INSERT INTO `producto`( `producto`) VALUES ("RADIADOR");
INSERT INTO `producto`( `producto`) VALUES ("REFLEJANTE");
INSERT INTO `producto`( `producto`) VALUES ("REGULADOR");
INSERT INTO `producto`( `producto`) VALUES ("REJILLA");
INSERT INTO `producto`( `producto`) VALUES ("RELAY");
INSERT INTO `producto`( `producto`) VALUES ("REPARTIDOR");
INSERT INTO `producto`( `producto`) VALUES ("REPUESTO");
INSERT INTO `producto`( `producto`) VALUES ("RESISTENCIA");
INSERT INTO `producto`( `producto`) VALUES ("RESORTE");
INSERT INTO `producto`( `producto`) VALUES ("RETEN");
INSERT INTO `producto`( `producto`) VALUES ("RIEL");
INSERT INTO `producto`( `producto`) VALUES ("RONDANA");
INSERT INTO `producto`( `producto`) VALUES ("ANTICONGELANTE ROSA 1LT");
INSERT INTO `producto`( `producto`) VALUES ("ANTICONGELANTE ROSA 20LT");
INSERT INTO `producto`( `producto`) VALUES ("ANTICONGELANTE ROSA 4LT");
INSERT INTO `producto`( `producto`) VALUES ("ROSHFRANS");
INSERT INTO `producto`( `producto`) VALUES ("ROTULA");
INSERT INTO `producto`( `producto`) VALUES ("SALPICADERA");
INSERT INTO `producto`( `producto`) VALUES ("SEGURO");
INSERT INTO `producto`( `producto`) VALUES ("SELENOIDE");
INSERT INTO `producto`( `producto`) VALUES ("SELLO");
INSERT INTO `producto`( `producto`) VALUES ("SENICERO");
INSERT INTO `producto`( `producto`) VALUES ("SENSOR");
INSERT INTO `producto`( `producto`) VALUES ("SHELLAC");
INSERT INTO `producto`( `producto`) VALUES ("SIGNO");
INSERT INTO `producto`( `producto`) VALUES ("SILICON");
INSERT INTO `producto`( `producto`) VALUES ("SINFIN");
INSERT INTO `producto`( `producto`) VALUES ("SOPORTE");
INSERT INTO `producto`( `producto`) VALUES ("SPOILER");
INSERT INTO `producto`( `producto`) VALUES ("SWITCH");
INSERT INTO `producto`( `producto`) VALUES ("TALERO");
INSERT INTO `producto`( `producto`) VALUES ("TAMBOR");
INSERT INTO `producto`( `producto`) VALUES ("JUG TAPAS PERTA CARIBE");
INSERT INTO `producto`( `producto`) VALUES ("TAPA");
INSERT INTO `producto`( `producto`) VALUES ("TAPETE");
INSERT INTO `producto`( `producto`) VALUES ("TAPON");
INSERT INTO `producto`( `producto`) VALUES ("TAVANCE");
INSERT INTO `producto`( `producto`) VALUES ("TEFLON");
INSERT INTO `producto`( `producto`) VALUES ("TENSOR");
INSERT INTO `producto`( `producto`) VALUES ("TERINAL");
INSERT INTO `producto`( `producto`) VALUES ("TERMOSTATO");
INSERT INTO `producto`( `producto`) VALUES ("TOLVA");
INSERT INTO `producto`( `producto`) VALUES ("TOMA");
INSERT INTO `producto`( `producto`) VALUES ("TORNILLO");
INSERT INTO `producto`( `producto`) VALUES ("TORRE");
INSERT INTO `producto`( `producto`) VALUES ("TRANSMISOR");
INSERT INTO `producto`( `producto`) VALUES ("TROMPO");
INSERT INTO `producto`( `producto`) VALUES ("TRIPOIDE");
INSERT INTO `producto`( `producto`) VALUES ("TUBO");
INSERT INTO `producto`( `producto`) VALUES ("TUERCA");
INSERT INTO `producto`( `producto`) VALUES ("TURBINA");
INSERT INTO `producto`( `producto`) VALUES ("VALVULA");
INSERT INTO `producto`( `producto`) VALUES ("VARILLA");
INSERT INTO `producto`( `producto`) VALUES ("VELOCIMETRO");
INSERT INTO `producto`( `producto`) VALUES ("VENTILADOR");
INSERT INTO `producto`( `producto`) VALUES ("ANTICONGELANTE VERDE 1LT");
INSERT INTO `producto`( `producto`) VALUES ("ANTICONGELANTE VERDE 20LT");
INSERT INTO `producto`( `producto`) VALUES ("ANTICONGELANTE VERDE 4LT");
INSERT INTO `producto`( `producto`) VALUES ("VOLANTE");
